version: "3"

services:
  cockpit-cms:
    build: ./.cockpit-build
    container_name: cockpit.app
    ports:
      - 8080:80
    volumes:
      - ./storage:/var/www/html/storage
    networks:
      static-network:
        ipv4_address: 172.20.64.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16